"""Pluggable AI Inference Engine Base Classes and Contracts."""

from abc import ABC, abstractmethod
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class BoundingBox(BaseModel):
    """Normalized bounding box coordinates (0.0 to 1.0)."""
    x_min: float = Field(..., ge=0.0, le=1.0)
    y_min: float = Field(..., ge=0.0, le=1.0)
    x_max: float = Field(..., ge=0.0, le=1.0)
    y_max: float = Field(..., ge=0.0, le=1.0)


class FindingCandidate(BaseModel):
    """Candidate anomaly detection generated by an inference engine."""
    defect_class: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    bbox: BoundingBox
    polygon_mask: Optional[List[List[float]]] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class FrameInferenceResult(BaseModel):
    """Inference result for a single frame."""
    frame_index: int
    timestamp_ms: float
    engine_name: str
    model_version: str
    is_simulated: bool
    findings: List[FindingCandidate] = Field(default_factory=list)


class BaseInferenceEngine(ABC):
    """
    Abstract interface for all KeeAInu defect detection engines.
    Ensures models are decoupled from the application and testable in isolation.
    """
    
    @property
    @abstractmethod
    def engine_name(self) -> str:
        """Name of the inference engine."""
        pass
        
    @property
    @abstractmethod
    def model_version(self) -> str:
        """Version or checkpoint tag of the model."""
        pass
        
    @property
    @abstractmethod
    def is_simulated(self) -> bool:
        """True if the engine produces simulated/mock results rather than real ML predictions."""
        pass

    @abstractmethod
    async def infer_frame(
        self,
        frame_bytes: bytes,
        frame_index: int,
        timestamp_ms: float,
        confidence_threshold: float = 0.5
    ) -> FrameInferenceResult:
        """Run defect candidate detection on a single frame."""
        pass
